import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sreema' at '6/1/16 3:39 PM' with Gradle 2.13
 *
 * @author sreema, @date 6/1/16 3:39 PM
 */
public class TestingRXTest {
    @Test public void testSomeLibraryMethod() {
        TestingRX classUnderTest = new TestingRX();
       // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
